pull_request_rules:
  - name: Automatic merge on approval
    conditions:
    - or:
      - check-success=Validate JSONs
      - -files~=^(!?changelogs/)
      - -files~=^(!?builds/)
    actions:
      merge:
        method: merge
